name: 'JUCE 6 Windows Build'
description: 'Build a JUCE 6 project on windows using cmake'
runs:
  using: 'composite'
  steps: 
    - run: |
        cmake -B build
        cmake --build build
      shell: bash
